### PR TITLE
Team 404

### PR DESCRIPTION
**Pull request by al-kheerow**

### CODE REVIEW

**Review by osamaakb — COMMENTED** [review]
Good job guys, I like the one you picked, I just want to mention that your README file still misses a couple of things I will list here:
- Screenshots (desktop, tablet, and mobile versions) of the pages you'll build
- Who will be working on each part of the website
- Which CSS Framework you'll be using
- How much of the website do you plan on finishing by May 5 (Tuesday)
please try to submit another pull request today with the missing information included 😊

**Comment by osamaakb** [comment]
I noticed one other small thing, The design doesn't seem to have a lot of components to it though and I worry that it doesn't have enough work for all of you. There are 2 options you can choose from that I can see moving forward:

1. You explain to me what each team member will be working on so I get a better estimation of how much work each of you will be dedicating to the project.
2. You choose a different design that has more components, sections, or pages.
I don't mean to make this difficult, I just want to make sure that you're all getting enough practice out of this.

**Comment by al-kheerow** [comment]
We included everything you asked for in the new commit

**Review by osamaakb — APPROVED** [review]
Good job 404, thanks for doing the changes in time 🙌

**Comment by al-kheerow** [comment]
Fixing the README.md

**Pull request closed without merging**
