### PR TITLE
add the project info

### PR DESCRIPTION
**Pull request by yazenfiras**

### CODE REVIEW

**Review by wisammechano — CHANGES_REQUESTED** [review]
Your pull request should have a directory with the team name with all the files inside. For example:

| /Fantastic4Team
|___ /mockup
|     |____ screenshot-desktop.png
|     |____ screenshot-mobile.png
|___ readme.md
|___ index.html
|___ style.css

**Comment by yazenfiras** [comment]
ok wissam i will do it now

**Comment by yazenfiras** [comment]
is it okay now Wissam?

**Comment by wisammechano** [comment]
accepted. make sure to add a mobile mockup at some point. you can start working on it right away. Re-open the pull request on Tuesday

**Comment by yazenfiras** [comment]
ok thank you we will start working on it .but will you provide us the photo
and the font and these stuff of the page or not?

**Pull request closed without merging**
